### ISSUE TITLE
Consensus not working

### ISSUE THREAD

**Issue by Saillantslab** [yechengxi/DBG2OLC#45]
Good morning, 

I'm trying to go through the tutorial and have made it as far as the consensus step and this is my output
```
[meeseeks] ~/Sparc/utility$ sh ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir >cns_log.txt
rm: cannot remove './consensus_dir/backbone-*': No such file or directory
  File "./split_reads_by_backbone.py", line 43
    print tuple[0]
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print tuple[0])?
ls: cannot access './consensus_dir/*.reads.fasta': No such file or directory
cat: './consensus_dir/*.consensus.fasta': No such file or directory
```
I have changed the `blasr` code to the double-dashes as specified, but I cannot seem to get this off the ground. Is `./consensus_dir` an empty folder I need to make myself (which I have), and there is no `reads.fasta` file. I'm just a little confused at this step and would greatly appreciate any help.

**Comment by jdmontenegro** [comment]
Hi Saillanslab,

I ran into the same issue and managed to make it work by changing variuos parts of the script. In my case Below is the modified script that is working.

```
#!/usr/bin/env bash

###
# USAGE: ./split_and_run_sparc.sh [BACKBONE_FASTA] [CONSENSUS_FASTA] [READS_FASTA] [OUTPUT_DIR] [ITERATIONS] ###

backbone_fasta=$1
consensus_fasta=$2
reads_fasta=$3
split_dir=$4
iterations=$5



#clean the directory first
rm ${split_dir}/backbone-*

echo "split_reads_by_backbone.py -b ${backbone_fasta} -o ${split_dir} -r ${reads_fasta} -c ${consensus_fasta}"
split_reads_by_backbone.py -b ${backbone_fasta} -o ${split_dir} -r ${reads_fasta} -c ${consensus_fasta}

for file in ${split_dir}/*.reads.fasta; do
    chunk=`basename ${file}`
    chunk="${chunk%%.*}"

    cmd=""
    for iter in `seq 1 ${iterations}`; do

        #echo $iter

        cmd+="blasr --nproc 128 ${split_dir}/${chunk}.reads.fasta ${split_dir}/${chunk}.fasta --bestn 1 -m 5 --minMatch 19 --out ${split_dir}/${chunk}.mapped.m5; "

        cmd+="Sparc m ${split_dir}/${chunk}.mapped.m5 b ${split_dir}/${chunk}.fasta k 1 c 2 g 1 HQ_Prefix Contig boost 5 t 0.2 o ${split_dir}/${chunk}; "

        if [ ${iter} -lt ${iterations} ]
        then
        #rename
        cmd+="mv ${split_dir}/${chunk}.consensus.fasta ${split_dir}/${chunk}.fasta;"
        fi

    done

    echo $cmd
    eval $cmd


    #to save space
    cmd="rm ${split_dir}/${chunk}.mapped.m5"
    echo $cmd
    eval $cmd
    cmd="rm ${split_dir}/${chunk}.reads.fasta"
    echo $cmd
    eval $cmd

done

cmd="for i in ${split_dir}/*.consensus.fast; do cat ${i} >> ${split_dir}/final_assembly.fasta; done"
echo=$cmd
eval $cmd
```

However, I find different issue. After finishing the consensus step, the final consensus is less than half the length of the raw backbone. I find that concerning and would like to now if that is the expected behavior of the consensus step.

Kind regards,

**Comment by yechengxi** [comment]
Our code was written in python2, @Saillantslab was using python 3. I think that created the problem.

@jdmontenegro may I know the coverage of your data? It shouldn't happen if proper parameters are used.

**Comment by jdmontenegro** [comment]
Hi Chengxi Ye,

I have 60X of illumina data and 10X PacBio data. The backbone_raw
statistics look pretty good, but the consensus is only half the length of
the backbone (i.e. backbone = 1.1 Gb, consensus = 560 Mbp)

Any ideas what could be going on?

Cheers,

2018-06-05 2:22 GMT+10:00 Chengxi Ye <notifications@github.com>:

**Comment by yechengxi** [comment]
Please take a look at the parameters used in sparc:
https://github.com/yechengxi/Sparc
In your case try to set all the values small, k 1 g 1 c 1 t 0.0

**Comment by pdimens** [comment]
Thanks for replying to @Saillantslab (that was me, didn't realize I was logged into our laboratory's account). I just remembered that I had posted here, so please forgive my silence. I had realized the issue was the machine defaulting to python3, so I had put it on the backburner for a bit despite trying to change the config scripts to python and still not having it compile correctly. I've since solved the issue in record time by installing everything into a `conda` environment and now everything works great.

Thank you for writing back and apologies again for not responding (I wasn't getting the confirmation emails on this account). Also, thank you for writing this software!

**Comment by pradeepphule** [comment]
$ ./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt ctg_pb.fasta ./consensus_dir 2 >cns_log.txt
  File "split_reads_by_baillumina_assembly_pacbioreads_combine.fastackbone.py", line 43
    print tuple[0]
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tuple[0])?

**Comment by pradeepphule** [comment]
./split_and_run_sparc.sh backbone_raw.fasta DBG2OLC_Consensus_info.txt illumina_assembly_pacbioreads_combine.fasta ./consensus_dir 2 >cns_log.txt
  File "split_reads_by_backbone.py", line 43
    print tuple[0]
              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(tuple[0])?



i am getting this error please help above solution doesnt work for me, i checked with python and python3 as well
